website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Gps(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    lat = db.Column(db.Float, nullable=False)
    lon = db.Column(db.Float, nullable=False)
    alt = db.Column(db.Float)
    speed = db.Column(db.Float)
    time = db.Column(db.DateTime, nullable=False)
    vehicle_id = db.Column(db.String(45), db.ForeignKey('vehicle.reg'))
    
# # Retrieve the latest location for each vehicle
# subquery = db.session.query(
#     Gps.vehicle_id,
#     func.max(Gps.time).label('max_time')
# ).group_by(Gps.vehicle_id).subquery()

# latest_locations = db.session.query(
#     Gps
# ).join(
#     subquery,
#     db.and_(
#         Gps.vehicle_id == subquery.c.vehicle_id,
#         Gps.time == subquery.c.max_time
#     )
# ).all()

class Vehicle(db.Model):
    reg = db.Column(db.String(45),primary_key=True, unique=True, nullable=False)
    name = db.Column(db.String(45), unique=True, nullable=False)
    brand = db.Column(db.String(45), nullable=False)
    color = db.Column(db.String(45))
    seats = db.Column(db.Integer, nullable=False)
    inServ = db.Column(db.Date)
    outServ = db.Column(db.Date)
    gpss = db.relationship('Gps')

def __init__(self, reg, brand, color, seats, inServ, outServ):
    self.reg = reg
    self.brand = brand
    self.color = color
    self.seats = seats
    self.inServ = inServ
    self.outServ = outServ

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(100), unique=True, nullable=False)
    username = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import func
from os import path
from flask_login import LoginManager
import folium
import redis

db = SQLAlchemy()
DB_NAME = "baseD.db"


def create_app():

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret key'
#    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:11111111@localhost/baseD'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    # r = redis.Redis(host='localhost', port=6379, db=0)

    from .models import User, Vehicle, Gps

    # create_database(app)


    
    with app.app_context():
        db.create_all()
        subquery = db.session.query(
            Gps.vehicle_id,
            func.max(Gps.time).label('max_time')
        ).group_by(Gps.vehicle_id).subquery()

        vehicles = db.session.query(
            Gps
        ).join(
            subquery,
            db.and_(
                Gps.vehicle_id == subquery.c.vehicle_id,
                Gps.time == subquery.c.max_time
            )
        ).all()

    if len(vehicles) > 0:
        map = folium.Map(location=[vehicles[0].lat, vehicles[0].lon], zoom_start=15)
    else:
        map = folium.Map(location=[36.7958604, 10.1805513], zoom_start=15)

    for Gps in vehicles:
        folium.Marker([Gps.lat, Gps.lon],
                      tooltip=f"<b>ID: {Gps.vehicle_id}</b><br><b>Latitude:</b> {Gps.lat}<br><b>Longitude:</b> {Gps.lon}<br><b>Altitude:</b> {Gps.alt} m<br><b>Speed:</b> {Gps.speed} km/h<br><b>Time:</b> {Gps.time}",
                      icon=folium.Icon(icon='train',prefix='fa')).add_to(map),

    map.save('website/templates/map.html')


    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


# def create_database(app):
#     if not path.exists('website/' + DB_NAME):
#         db.create_all(app=app)
#         print('Created Database!')

website/auth.py
from crypt import methods
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Vehicle
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/home')
@login_required
def home():
    data = Vehicle.query.all()
    return render_template('home.html', vehicles = data)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('auth.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Username does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(username=username).first()
        if user:
            flash('Username already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 2:
            flash('Username must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('auth.home'))

    return render_template("sign_up.html", user=current_user)


@auth.route('/admin')
@login_required
def admin():
    data = Vehicle.query.all()
    id = current_user.id
    if id == 1:
        return render_template("admin.html", vehicles = data)
    else:
        flash("You must be the Admin to access the Admin Page.")
        return redirect(url_for('login.html'))

@auth.route('/insert', methods = ['POST'])
def insert():
    from .models import Vehicle
    if request.method == 'POST':
        new_vehicle = Vehicle(reg= request.form['reg'],
        name= request.form['name'],
        brand= request.form['brand'],
        color= request.form['color'],
        seats= request.form['seats'],
        inServ= request.form['inServ'],
        outServ= request.form['outServ'])
        
        db.session.add(new_vehicle)
        db.session.commit()
        
        flash("Vehicle added successfully", category='success')
        return redirect(url_for('auth.admin'))

@auth.route('/update', methods = ['GET', 'POST'])
def update():
    from .models import Vehicle
    if request.method == 'POST':
        v_data=Vehicle.query.get(request.form.get('reg'))
        
        v_data.reg = request.form['reg']
        v_data.name= request.form['name']
        v_data.brand = request.form['brand']
        v_data.color = request.form['color']
        v_data.seats = request.form['seats']
        v_data.inServ = request.form['inServ']
        v_data.outServ = request.form['outServ']

        db.session.commit()
        flash("Vehicle updated successfully", category='success')
        return redirect(url_for('auth.admin'))

@auth.route('/delete/<reg>/', methods = ['GET', 'POST'])
def delete(reg):
    from .models import Vehicle
    v_del=Vehicle.query.get(reg)
    db.session.delete(v_del)
    db.session.commit()
    flash("Vehicle deleted successfully", category='success')
    return redirect(url_for('auth.admin'))

website/views.py
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user
from . import db

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():

    return render_template("home.html", user=current_user)

website/templates/admin.html
{% extends "base.html" %}
{% block title %}Vehicle Managment{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col md-12">
            <div class="jumbotron p-3">
                <h2>Manage <b>Vehicles</b><button type="button" class="btn btn-success float-right"
                data-toggle="modal" data-target="#mymodal">Add new Vehicle</button> </h2>


                <table class="table table-hover table-dark">
                    <tr>
                        <th>Registration</th>
                        <th>Name</th>
                        <th>Brand</th>
                        <th>Color</th>
                        <th>Number of Seats</th>
                        <th>Commissioning date</th>
                        <th>Retirement date</th>
                        <th>Action</th>
                    </tr>
                    
                    {% for row in vehicles %}
                    <tr>
                        <td>{{row.reg}}</td>
                        <td>{{row.name}}</td>
                        <td>{{row.brand}}</td>
                        <td>{{row.color}}</td>
                        <td>{{row.seats}}</td>
                        <td>{{row.inServ}}</td>
                        <td>{{row.outServ}}</td>
                        <td>
                            <a href="/update/{{row.reg}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.reg}}">Edit</a>
                            <a href="/delete/{{row.reg}}" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete? ')">Delete</a>

                        </td>

                    </tr>
                    

                    <div id="modaledit{{row.reg}}" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title">Update Info</h4>
                                </div>
                                <div class="modal-body">
                                    <form action="{{url_for('auth.update')}}" method="POST">
                                        
                                        <div class="form-group">
                                            <label>Name:</label>
                                            <input type="text" class="form-control" name="name" value="{{row.name}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Brand:</label>
                                            <input type="text" class="form-control" name="brand" value="{{row.brand}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Color:</label>
                                            <input type="text" class="form-control" name="color" value="{{row.color}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Number of Seats:</label>
                                            <input type="number" class="form-control" name="seats" value="{{row.seats}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Commissioning date:</label>
                                            <input type="date" class="form-control" name="inServ" value="{{row.inServ}}">
                                        </div>
                                        <div class="form-group">
                                            <label>Retirement date:</label>
                                            <input type="date" class="form-control" name="outServ" value="{{row.outServ}}">
                                        </div>
        
                                        <div class="form-group">
                                            <button class="btn btn-primary" type="submit">Update</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                    {% endfor %}
                </table>
            </div>
        
            <div id="mymodal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Add Vehicle</h4>
                        </div>
                        <div class="modal-body">
                            <form action="{{url_for('auth.insert')}}" method="POST">
                                <div class="form-group">
                                    <label>Registration:</label>
                                    <input type="text" class="form-control" name="reg" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Name:</label>
                                    <input type="text" class="form-control" name="name" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Brand:</label>
                                    <input type="text" class="form-control" name="brand" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Color:</label>
                                    <input type="text" class="form-control" name="color" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Number of Seats:</label>
                                    <input type="number" class="form-control" name="seats" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Commissioning date:</label>
                                    <input type="date" class="form-control" name="inServ" required="1">
                                </div>
                                <div class="form-group">
                                    <label>Retirement date:</label>
                                    <input type="date" class="form-control" name="outServ" required="1">
                                </div>

                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Add Vehicle</button>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="shortcut icon" type="image/ico" href="static/favicon.ico" />
    
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="style.css" />

    <title>{% block title %}Home{% endblock %}</title>
    <style>
      .col-fixed { position:relative; min-height:1px; padding-right:15px; padding-left:15px; float:left; width:100%;  }
      .col-fluid { position:relative; min-height:1px; padding-right:15px; padding-left:15px; float:left; width:100%;  }

      @media (min-width: 768px) and (max-width: 991px) {    
          .col-fixed { width:260px; }
          .col-fluid { width:calc(100% - 350px);}        
      }                                          
      @media (min-width: 992px) and (max-width: 1199px) {
          .col-fixed { width:260px; }
          .col-fluid { width:calc(100% - 350px);}
      }
      @media (min-width: 1200px) {
          .col-fixed { width:260px; }
          .col-fluid { width:calc(100% - 350px);}
      }

      body {
          background-color: #fbfbfb;
          font-family: "Lato", sans-serif;
          padding-left: 270px;
        }
        @media (min-width: 991.98px) {
          main {
            padding-left: 240px;
          }
        }
         
        /* Sidebar */
        .sidebar {
          position: fixed;
          top: 0;
          bottom: 0;
          left: 0;
          padding: 58px 0 0; /* Height of navbar */
          box-shadow: 0 2px 5px 0 rgb(0 0 0 / 5%), 0 2px 10px 0 rgb(0 0 0 / 5%);
          width: 240px;
          z-index: 600;
        }
        
        @media (max-width: 991.98px) {
          .sidebar {
            width: 100%;
          }
        }
        .sidebar .active {
          border-radius: 5px;
          box-shadow: 0 2px 5px 0 rgb(0 0 0 / 16%), 0 2px 10px 0 rgb(0 0 0 / 12%);
        }
        
        .sidebar-sticky {
          position: relative;
          top: 0;
          height: calc(100vh - 48px);
          padding-top: 0.5rem;
          overflow-x: hidden;
          overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
        }


            .sidenav {
              height: 100%;
              width: 270px;
              position: fixed;
              z-index: 1;
              top: 0;
              left: 0;
              background-color: rgb(0, 77, 77);
              overflow-x: hidden;
              padding-top: 10px;
            }
            .logo {
            text-align: center;
            width: auto;
            height: auto;
            }
            .sidenav a {
              padding: 6px 8px 6px 16px;
              text-decoration: none;
              font-size: 25px;
              color: #818181;
              display: block;
            }
            
            .sidenav a:hover {
              color: #f1f1f1;
            }
            .navbar-nav{
              padding-left: 20px;
            }

            .main {
              margin-left: 160px; /* Same as the width of the sidenav */
              font-size: 28px; /* Increased text to enable scrolling */
              padding: 0px 10px;
            }
            
            @media screen and (max-height: 450px) {
              .sidenav {padding-top: 15px;}
              .sidenav a {font-size: 18px;}
            }
            .alert {

              z-index: 6;
            }

      </style>
  
  </head>
  <body>
   

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
   <div class="sidenav" id="navbar">
    <div class="logo py-4">
      <a href="http://127.0.0.1:5000/home">
        <img src="{{url_for('static', filename='transtu_logo.png')}}" alt="transtu_logo" width=auto height="65"/>
      </a>
    </div>
    <br>
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="{{ url_for('auth.home')}}"><i class="fa fa-fw fa-bus"></i>    Vehicles</a>
            <hr>
            {% if current_user.id == 1 %}         
              <a class="nav-item nav-link" id="admin" href="{{ url_for('auth.admin')}}"><i class="fa fa-fw fa-cogs"></i>    Manage Vehicles</a>
            {% endif %}
            <hr>
            <a class="nav-item nav-link" id="logout" href="{{ url_for('auth.logout')}}"><i class="fa fa-fw fa-sign-out"></i>    Logout</a>
          {% else %}
          <hr>
            <a class="nav-item nav-link" id="login" href="{{ url_for('auth.login')}}"><i class="fa fa-fw fa-sign-in"></i>    Login</a>
            <hr>
            <a class="nav-item nav-link" id="signUp" href="{{ url_for('auth.sign_up')}}"><i class="fa fa-fw fa-user"></i>    Sign Up</a>
          {% endif %}
        </div>
      </div>
    
    <div class="main">
      
    </div>
       

    
  
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
 
  </body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Fleet Tracking{% endblock %}

{% block content %}

    
<!-- <h1 align="center">Location: </h1>
         <div class="dropdown" name= vehicle method="GET" action="/" align="center">
                <button class="btn btn-primary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" >Vehicles
                <span class="caret"></span></button>
                <ul class="dropdown-menu" >
                    {% for row in vehicles %}
                        <li>
                            <a href="http://127.0.0.1:5500/website/templates/map.html" target="iframe_map">
                                <option value="{{row.id}}">{{row.name}}</option>
                            </a>
                        </li>    
                            <li class="divider"></li>
                    {% endfor %}
                </ul>
            </div> -->
        <br>
       
  <div class="main">
        <iframe 
            name="iframe_map" 
            src="http://127.0.0.1:5500/website/templates/map.html" 
            width="700" 
            height="500"
            style="position:fixed;
             top: 50px; left: 270px; bottom:0; right:0; 
             width:100%; height:100%; z-index: 0;
             border:none; margin:0; padding:0; overflow:hidden; 
            z-index:999999">
            Your browser doesn't support iframes
        </iframe>
    </div> 
        
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="username">Username</label>
    <input
      type="text"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter Username"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/map.html
<!DOCTYPE html>
<html>
<head>
    
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    
        <script>
            L_NO_TOUCH = false;
            L_DISABLE_3D = false;
        </script>
    
    <style>html, body {width: 100%;height: 100%;margin: 0;padding: 0;}</style>
    <style>#map {position:absolute;top:0;bottom:0;right:0;left:0;}</style>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>
    
            <meta name="viewport" content="width=device-width,
                initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <style>
                #map_e50ef31faa7939ca6fde9dd3584ec557 {
                    position: relative;
                    width: 100.0%;
                    height: 100.0%;
                    left: 0.0%;
                    top: 0.0%;
                }
            </style>
        
</head>
<body>
    
    
            <div class="folium-map" id="map_e50ef31faa7939ca6fde9dd3584ec557" ></div>
        
</body>
<script>
    
    
            var map_e50ef31faa7939ca6fde9dd3584ec557 = L.map(
                "map_e50ef31faa7939ca6fde9dd3584ec557",
                {
                    center: [36.7958, 10.1798],
                    crs: L.CRS.EPSG3857,
                    zoom: 15,
                    zoomControl: true,
                    preferCanvas: false,
                }
            );

            

        
    
            var tile_layer_42f5a03e66461d5dfa5b44c5f5fe4606 = L.tileLayer(
                "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                {"attribution": "Data by \u0026copy; \u003ca href=\"http://openstreetmap.org\"\u003eOpenStreetMap\u003c/a\u003e, under \u003ca href=\"http://www.openstreetmap.org/copyright\"\u003eODbL\u003c/a\u003e.", "detectRetina": false, "maxNativeZoom": 18, "maxZoom": 18, "minZoom": 0, "noWrap": false, "opacity": 1, "subdomains": "abc", "tms": false}
            ).addTo(map_e50ef31faa7939ca6fde9dd3584ec557);
        
    
            var marker_d31ddca43d60673938cfd5ae762470bc = L.marker(
                [36.7958, 10.1798],
                {}
            ).addTo(map_e50ef31faa7939ca6fde9dd3584ec557);
        
    
            var icon_4f49b0e1b9bc3494b205566da6629d23 = L.AwesomeMarkers.icon(
                {"extraClasses": "fa-rotate-0", "icon": "train", "iconColor": "white", "markerColor": "blue", "prefix": "fa"}
            );
            marker_d31ddca43d60673938cfd5ae762470bc.setIcon(icon_4f49b0e1b9bc3494b205566da6629d23);
        
    
            marker_d31ddca43d60673938cfd5ae762470bc.bindTooltip(
                `<div>
                     <b>ID: M220</b><br><b>Latitude:</b> 36.7958<br><b>Longitude:</b> 10.1798<br><b>Altitude:</b> 11.0 m<br><b>Speed:</b> 22.0 km/h<br><b>Time:</b> 2023-05-15 11:42:05
                 </div>`,
                {"sticky": true}
            );
        
    
            var marker_cb04fa04ea3780ae68f3b6c20bafe951 = L.marker(
                [36.8007, 10.1922],
                {}
            ).addTo(map_e50ef31faa7939ca6fde9dd3584ec557);
        
    
            var icon_fa2344a7f0d529c182c627a36df3b839 = L.AwesomeMarkers.icon(
                {"extraClasses": "fa-rotate-0", "icon": "train", "iconColor": "white", "markerColor": "blue", "prefix": "fa"}
            );
            marker_cb04fa04ea3780ae68f3b6c20bafe951.setIcon(icon_fa2344a7f0d529c182c627a36df3b839);
        
    
            marker_cb04fa04ea3780ae68f3b6c20bafe951.bindTooltip(
                `<div>
                     <b>ID: R218</b><br><b>Latitude:</b> 36.8007<br><b>Longitude:</b> 10.1922<br><b>Altitude:</b> 3.0 m<br><b>Speed:</b> 0.0 km/h<br><b>Time:</b> 2023-05-15 12:35:53
                 </div>`,
                {"sticky": true}
            );
        
    
            var marker_55f743b3ef6aa96e07bb3c2833fa2ce2 = L.marker(
                [36.8062, 10.1807],
                {}
            ).addTo(map_e50ef31faa7939ca6fde9dd3584ec557);
        
    
            var icon_5246e50545502e39556ec3c067643847 = L.AwesomeMarkers.icon(
                {"extraClasses": "fa-rotate-0", "icon": "train", "iconColor": "white", "markerColor": "blue", "prefix": "fa"}
            );
            marker_55f743b3ef6aa96e07bb3c2833fa2ce2.setIcon(icon_5246e50545502e39556ec3c067643847);
        
    
            marker_55f743b3ef6aa96e07bb3c2833fa2ce2.bindTooltip(
                `<div>
                     <b>ID: B2182</b><br><b>Latitude:</b> 36.8062<br><b>Longitude:</b> 10.1807<br><b>Altitude:</b> 7.0 m<br><b>Speed:</b> 13.0 km/h<br><b>Time:</b> 2023-05-17 10:17:33
                 </div>`,
                {"sticky": true}
            );
        
</script>
</html>